set(CMAKE_SYSTEM Generic)
set(CMAKE_SYSTEM_NAME Generic)
set(CMAKE_SYSTEM_PROCESSOR ARM)
set(CMAKE_CROSSCOMPILING 1)
# Reset generator. Wehn MSVC is detected it overrides the generator and prevents
# use of the arm64 toolchain
set(CMAKE_GENERATOR '')

set(TOOLCHAIN_DIR ${CMAKE_BINARY_DIR}/external/aarch64-linux/toolchain)

set(BINUTILS_PATH ${TOOLCHAIN_DIR}/bin)
get_filename_component(${TOOLCHAIN_DIR} ${BINUTILS_PATH} DIRECTORY)

SET(CMAKE_C_COMPILER ${BINUTILS_PATH}/aarch64-none-linux-gnu-gcc.exe)
SET(CMAKE_CXX_COMPILER ${BINUTILS_PATH}/aarch64-none-linux-gnu-g++.exe)
SET(CMAKE_ASM_COMPILER ${CMAKE_C_COMPILER})
SET(CMAKE_C_COMPILER_WORKS 1)
SET(CMAKE_CXX_COMPILER_WORKS 1)

SET(TOOLCHAIN_NAME "aarch64-none-linux-gnu 12.1")

SET(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)
SET(CMAKE_SYSROOT  ${TOOLCHAIN_DIR}/aarch64-none-linux-gnu/libc)

SET(CMAKE_FIND_ROOT_PATH ${TOOLCHAIN_DIR})
SET(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM  NEVER)
SET(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY  ONLY)
SET(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE  ONLY)

set(CMAKE_C_FLAGS "--sysroot=${CMAKE_SYSROOT}")
set(CMAKE_CXX_FLAGS "--sysroot=${CMAKE_SYSROOT}")