# Set compilers and toolchain

set(CMAKE_SYSTEM Generic)
set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR ARM64)

if (NOT APPLE)

    set(TOOLCHAIN_DIR ${CMAKE_SOURCE_DIR}/external/aarch64-linux/toolchain)
    set(BINUTILS_PATH ${TOOLCHAIN_DIR}/bin)

    SET(CMAKE_C_COMPILER ${BINUTILS_PATH}/aarch64-none-linux-gnu-gcc.exe)
    SET(CMAKE_CXX_COMPILER ${BINUTILS_PATH}/aarch64-none-linux-gnu-g++.exe)
    SET(CMAKE_ASM_COMPILER ${CMAKE_C_COMPILER})
    SET(CMAKE_C_COMPILER_WORKS 1)
    SET(CMAKE_CXX_COMPILER_WORKS 1)

    SET(TOOLCHAIN_NAME "aarch64-none-linux-gnu 12.1")

    SET(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)
    SET(CMAKE_SYSROOT  ${TOOLCHAIN_DIR}/aarch64-none-linux-gnu/libc)

    SET(CMAKE_FIND_ROOT_PATH ${TOOLCHAIN_DIR})
    SET(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM  NEVER)
    SET(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY  ONLY)
    SET(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE  ONLY)

    # Set system root aka where to find libs
    set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} --sysroot=${CMAKE_SYSROOT}")
    set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} --sysroot=${CMAKE_SYSROOT}")
endif ()